ci: test

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -6,8 +6,13 @@ if ! npm run format; then
   exit 1
 fi
 
-if ! npx prettier —write .; then
+if ! npx prettier --write .; then
   echo "Error: Linting failed. Please fix the issues before committing."
+  exit 1
+fi
+
+if ! npm run lint; then
+  echo "Error: Code linting failed. Please fix the issues before committing."
   exit 1
 fi
 
